=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::AzureResourceManagerCommonTypesEncryption
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::AzureResourceManagerCommonTypesEncryption do
  #let(:instance) { AzureRest::AzureResourceManagerCommonTypesEncryption.new }

  describe 'test an instance of AzureResourceManagerCommonTypesEncryption' do
    it 'should create an instance of AzureResourceManagerCommonTypesEncryption' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::AzureResourceManagerCommonTypesEncryption)
    end
  end

  describe 'test attribute "infrastructure_encryption"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "customer_managed_key_encryption"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
