=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::BlobAccessPointConnectionTestStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::BlobAccessPointConnectionTestStatus do
  #let(:instance) { AzureSDK::BlobAccessPointConnectionTestStatus.new }

  describe 'test an instance of BlobAccessPointConnectionTestStatus' do
    it 'should create an instance of BlobAccessPointConnectionTestStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::BlobAccessPointConnectionTestStatus)
    end
  end

end
