=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::HttpProtocol
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::HttpProtocol do
  #let(:instance) { AzureSDK::HttpProtocol.new }

  describe 'test an instance of HttpProtocol' do
    it 'should create an instance of HttpProtocol' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::HttpProtocol)
    end
  end

end
