=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::ImmutabilityPolicyProperty
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::ImmutabilityPolicyProperty do
  #let(:instance) { AzureSDK::ImmutabilityPolicyProperty.new }

  describe 'test an instance of ImmutabilityPolicyProperty' do
    it 'should create an instance of ImmutabilityPolicyProperty' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::ImmutabilityPolicyProperty)
    end
  end

  describe 'test attribute "immutability_period_since_creation_in_days"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "allow_protected_append_writes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "allow_protected_append_writes_all"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
