=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::NetworkSecurityPerimeterConfigurationProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::NetworkSecurityPerimeterConfigurationProperties do
  #let(:instance) { AzureRest::NetworkSecurityPerimeterConfigurationProperties.new }

  describe 'test an instance of NetworkSecurityPerimeterConfigurationProperties' do
    it 'should create an instance of NetworkSecurityPerimeterConfigurationProperties' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::NetworkSecurityPerimeterConfigurationProperties)
    end
  end

  describe 'test attribute "provisioning_state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "provisioning_issues"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "network_security_perimeter"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "resource_association"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "profile"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
