=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::ObjectReplicationPolicyFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::ObjectReplicationPolicyFilter do
  #let(:instance) { AzureSDK::ObjectReplicationPolicyFilter.new }

  describe 'test an instance of ObjectReplicationPolicyFilter' do
    it 'should create an instance of ObjectReplicationPolicyFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::ObjectReplicationPolicyFilter)
    end
  end

  describe 'test attribute "prefix_match"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "min_creation_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
