=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::StorageAccountMigrationProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::StorageAccountMigrationProperties do
  #let(:instance) { AzureRest::StorageAccountMigrationProperties.new }

  describe 'test an instance of StorageAccountMigrationProperties' do
    it 'should create an instance of StorageAccountMigrationProperties' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::StorageAccountMigrationProperties)
    end
  end

  describe 'test attribute "target_sku_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "migration_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "migration_failed_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "migration_failed_detailed_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
