# frozen_string_literal: true

module AzureRest
  module Sql
    autoload :AdministratorType, "azure_rest/sql/models/administrator_type.rb"
    autoload :CheckNameAvailabilityReason, "azure_rest/sql/models/check_name_availability_reason.rb"
    autoload :CheckNameAvailabilityRequest, "azure_rest/sql/models/check_name_availability_request.rb"
    autoload :CheckNameAvailabilityResourceType, "azure_rest/sql/models/check_name_availability_resource_type.rb"
    autoload :CheckNameAvailabilityResponse, "azure_rest/sql/models/check_name_availability_response.rb"
    autoload :ErrorAdditionalInfo, "azure_rest/sql/models/error_additional_info.rb"
    autoload :ErrorDetail, "azure_rest/sql/models/error_detail.rb"
    autoload :ErrorResponse, "azure_rest/sql/models/error_response.rb"
    autoload :ExternalGovernanceStatus, "azure_rest/sql/models/external_governance_status.rb"
    autoload :IdentityType, "azure_rest/sql/models/identity_type.rb"
    autoload :ImportExportOperationResult, "azure_rest/sql/models/import_export_operation_result.rb"
    autoload :ImportExportOperationResultProperties, "azure_rest/sql/models/import_export_operation_result_properties.rb"
    autoload :ImportNewDatabaseDefinition, "azure_rest/sql/models/import_new_database_definition.rb"
    autoload :MinimalTlsVersion, "azure_rest/sql/models/minimal_tls_version.rb"
    autoload :NetworkIsolationSettings, "azure_rest/sql/models/network_isolation_settings.rb"
    autoload :PrincipalType, "azure_rest/sql/models/principal_type.rb"
    autoload :PrivateEndpointConnectionProperties, "azure_rest/sql/models/private_endpoint_connection_properties.rb"
    autoload :PrivateEndpointConnectionRequestStatus, "azure_rest/sql/models/private_endpoint_connection_request_status.rb"
    autoload :PrivateEndpointProperty, "azure_rest/sql/models/private_endpoint_property.rb"
    autoload :PrivateEndpointProvisioningState, "azure_rest/sql/models/private_endpoint_provisioning_state.rb"
    autoload :PrivateLinkServiceConnectionStateActionsRequire, "azure_rest/sql/models/private_link_service_connection_state_actions_require.rb"
    autoload :PrivateLinkServiceConnectionStateProperty, "azure_rest/sql/models/private_link_service_connection_state_property.rb"
    autoload :PrivateLinkServiceConnectionStateStatus, "azure_rest/sql/models/private_link_service_connection_state_status.rb"
    autoload :ProxyResource, "azure_rest/sql/models/proxy_resource.rb"
    autoload :RefreshExternalGovernanceStatusOperationResult, "azure_rest/sql/models/refresh_external_governance_status_operation_result.rb"
    autoload :RefreshExternalGovernanceStatusOperationResultProperties, "azure_rest/sql/models/refresh_external_governance_status_operation_result_properties.rb"
    autoload :Resource, "azure_rest/sql/models/resource.rb"
    autoload :ResourceIdentity, "azure_rest/sql/models/resource_identity.rb"
    autoload :Server, "azure_rest/sql/models/server.rb"
    autoload :ServerCreateMode, "azure_rest/sql/models/server_create_mode.rb"
    autoload :ServerExternalAdministrator, "azure_rest/sql/models/server_external_administrator.rb"
    autoload :ServerListResult, "azure_rest/sql/models/server_list_result.rb"
    autoload :ServerNetworkAccessFlag, "azure_rest/sql/models/server_network_access_flag.rb"
    autoload :ServerPrivateEndpointConnection, "azure_rest/sql/models/server_private_endpoint_connection.rb"
    autoload :ServerProperties, "azure_rest/sql/models/server_properties.rb"
    autoload :ServerPublicNetworkAccessFlag, "azure_rest/sql/models/server_public_network_access_flag.rb"
    autoload :ServerUpdate, "azure_rest/sql/models/server_update.rb"
    autoload :ServerWorkspaceFeature, "azure_rest/sql/models/server_workspace_feature.rb"
    autoload :StorageKeyType, "azure_rest/sql/models/storage_key_type.rb"
    autoload :SystemData, "azure_rest/sql/models/system_data.rb"
    autoload :TrackedResource, "azure_rest/sql/models/tracked_resource.rb"
    autoload :UserIdentity, "azure_rest/sql/models/user_identity.rb"
    autoload :ServersApi, "azure_rest/sql/api/servers_api.rb"
  end
end
