=begin
#MySQLManagementClient

#The Microsoft Azure management API provides create, read, update, and delete functionality for Azure MySQL resources including servers, databases, firewall rules, VNET rules, log files and configurations with new business model.

The version of the OpenAPI document: 2024-12-30

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::FirewallRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FirewallRulesApi' do
  before do
    # run before each test
    @api_instance = AzureRest::FirewallRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FirewallRulesApi' do
    it 'should create an instance of FirewallRulesApi' do
      expect(@api_instance).to be_instance_of(AzureRest::FirewallRulesApi)
    end
  end

  # unit tests for firewall_rules_create_or_update
  # Creates a new firewall rule or updates an existing firewall rule.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param firewall_rule_name The name of the server firewall rule.
  # @param parameters The required parameters for creating or updating a firewall rule.
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'firewall_rules_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for firewall_rules_delete
  # Deletes a firewall rule.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param firewall_rule_name The name of the server firewall rule.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'firewall_rules_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for firewall_rules_get
  # Gets information about a server firewall rule.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param firewall_rule_name The name of the server firewall rule.
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'firewall_rules_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for firewall_rules_list_by_server
  # List all the firewall rules in a given server.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param [Hash] opts the optional parameters
  # @return [FirewallRuleListResult]
  describe 'firewall_rules_list_by_server test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
