=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module Compute
  # Properties of the Capacity reservation.
  class CapacityReservationProperties < ApiModelBase
    # A unique id generated and assigned to the capacity reservation by the platform which does not change throughout the lifetime of the resource.
    attr_accessor :reservation_id

    # Specifies the value of fault domain count that Capacity Reservation supports for requested VM size. **Note:** The fault domain count specified for a resource (like virtual machines scale set) must be less than or equal to this value if it deploys using capacity reservation. Minimum api-version: 2022-08-01.
    attr_accessor :platform_fault_domain_count

    # A list of all virtual machine resource ids that are associated with the capacity reservation.
    attr_accessor :virtual_machines_associated

    # The date time when the capacity reservation was last updated.
    attr_accessor :provisioning_time

    # The provisioning state, which only appears in the response.
    attr_accessor :provisioning_state

    attr_accessor :instance_view

    # Specifies the time at which the Capacity Reservation resource was created. Minimum api-version: 2021-11-01.
    attr_accessor :time_created

    attr_accessor :schedule_profile

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'reservation_id' => :'reservationId',
        :'platform_fault_domain_count' => :'platformFaultDomainCount',
        :'virtual_machines_associated' => :'virtualMachinesAssociated',
        :'provisioning_time' => :'provisioningTime',
        :'provisioning_state' => :'provisioningState',
        :'instance_view' => :'instanceView',
        :'time_created' => :'timeCreated',
        :'schedule_profile' => :'scheduleProfile'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'reservation_id' => :'String',
        :'platform_fault_domain_count' => :'Integer',
        :'virtual_machines_associated' => :'Array<SubResourceReadOnly>',
        :'provisioning_time' => :'Time',
        :'provisioning_state' => :'String',
        :'instance_view' => :'CapacityReservationInstanceView',
        :'time_created' => :'Time',
        :'schedule_profile' => :'ScheduleProfile'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AzureRest::CapacityReservationProperties` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AzureRest::CapacityReservationProperties`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'reservation_id')
        self.reservation_id = attributes[:'reservation_id']
      end

      if attributes.key?(:'platform_fault_domain_count')
        self.platform_fault_domain_count = attributes[:'platform_fault_domain_count']
      end

      if attributes.key?(:'virtual_machines_associated')
        if (value = attributes[:'virtual_machines_associated']).is_a?(Array)
          self.virtual_machines_associated = value
        end
      end

      if attributes.key?(:'provisioning_time')
        self.provisioning_time = attributes[:'provisioning_time']
      end

      if attributes.key?(:'provisioning_state')
        self.provisioning_state = attributes[:'provisioning_state']
      end

      if attributes.key?(:'instance_view')
        self.instance_view = attributes[:'instance_view']
      end

      if attributes.key?(:'time_created')
        self.time_created = attributes[:'time_created']
      end

      if attributes.key?(:'schedule_profile')
        self.schedule_profile = attributes[:'schedule_profile']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          reservation_id == o.reservation_id &&
          platform_fault_domain_count == o.platform_fault_domain_count &&
          virtual_machines_associated == o.virtual_machines_associated &&
          provisioning_time == o.provisioning_time &&
          provisioning_state == o.provisioning_state &&
          instance_view == o.instance_view &&
          time_created == o.time_created &&
          schedule_profile == o.schedule_profile
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [reservation_id, platform_fault_domain_count, virtual_machines_associated, provisioning_time, provisioning_state, instance_view, time_created, schedule_profile].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

  end
end