=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureRest
  module Compute
  class LifecycleHookActionState
    WAITING = "Waiting".freeze
    APPROVED = "Approved".freeze
    REJECTED = "Rejected".freeze

    def self.all_vars
      @all_vars ||= [WAITING, APPROVED, REJECTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if LifecycleHookActionState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #LifecycleHookActionState"
    end
  end
  end
end