=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module Compute
  class UpgradeState
    ROLLING_FORWARD = "RollingForward".freeze
    ROLLING_BACK = "RollingBack".freeze
    CANCELLED = "Cancelled".freeze
    COMPLETED = "Completed".freeze
    FAULTED = "Faulted".freeze

    def self.all_vars
      @all_vars ||= [ROLLING_FORWARD, ROLLING_BACK, CANCELLED, COMPLETED, FAULTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if UpgradeState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #UpgradeState"
    end
  end
  end
end