=begin
#KeyVaultManagementClient

#The Azure management API provides a RESTful set of web services that interact with Azure Key Vault.

The version of the OpenAPI document: 2026-05-15

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module KeyVault
  class CertificatePermissions
    ALL = "all".freeze
    GET = "get".freeze
    LIST = "list".freeze
    DELETE = "delete".freeze
    CREATE = "create".freeze
    IMPORT = "import".freeze
    UPDATE = "update".freeze
    MANAGECONTACTS = "managecontacts".freeze
    GETISSUERS = "getissuers".freeze
    LISTISSUERS = "listissuers".freeze
    SETISSUERS = "setissuers".freeze
    DELETEISSUERS = "deleteissuers".freeze
    MANAGEISSUERS = "manageissuers".freeze
    RECOVER = "recover".freeze
    PURGE = "purge".freeze
    BACKUP = "backup".freeze
    RESTORE = "restore".freeze

    def self.all_vars
      @all_vars ||= [ALL, GET, LIST, DELETE, CREATE, IMPORT, UPDATE, MANAGECONTACTS, GETISSUERS, LISTISSUERS, SETISSUERS, DELETEISSUERS, MANAGEISSUERS, RECOVER, PURGE, BACKUP, RESTORE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CertificatePermissions.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CertificatePermissions"
    end
  end
  end
end