=begin
#KeyVaultManagementClient

#The Azure management API provides a RESTful set of web services that interact with Azure Key Vault.

The version of the OpenAPI document: 2026-05-15

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module KeyVault
  class ProvisioningState
    SUCCEEDED = "Succeeded".freeze
    PROVISIONING = "Provisioning".freeze
    FAILED = "Failed".freeze
    UPDATING = "Updating".freeze
    DELETING = "Deleting".freeze
    ACTIVATED = "Activated".freeze
    SECURITY_DOMAIN_RESTORE = "SecurityDomainRestore".freeze
    RESTORING = "Restoring".freeze

    def self.all_vars
      @all_vars ||= [SUCCEEDED, PROVISIONING, FAILED, UPDATING, DELETING, ACTIVATED, SECURITY_DOMAIN_RESTORE, RESTORING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ProvisioningState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ProvisioningState"
    end
  end
  end
end