=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::BlobAccessPointConfigurationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlobAccessPointConfigurationsApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::BlobAccessPointConfigurationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlobAccessPointConfigurationsApi' do
    it 'should create an instance of BlobAccessPointConfigurationsApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::BlobAccessPointConfigurationsApi)
    end
  end

  # unit tests for blob_access_point_configurations_create
  # Creates or updates a Blob Access Point configuration.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param blob_access_point_configuration_name The name of the Blob Access Point configuration.
  # @param resource Resource create parameters.
  # @param [Hash] opts the optional parameters
  # @return [BlobAccessPointConfiguration]
  describe 'blob_access_point_configurations_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blob_access_point_configurations_delete
  # Delete a Blob Access Point configuration.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param blob_access_point_configuration_name The name of the Blob Access Point configuration.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'blob_access_point_configurations_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blob_access_point_configurations_get
  # Get the specified Blob Access Point configuration.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param blob_access_point_configuration_name The name of the Blob Access Point configuration.
  # @param [Hash] opts the optional parameters
  # @return [BlobAccessPointConfiguration]
  describe 'blob_access_point_configurations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blob_access_point_configurations_list_by_storage_account
  # List all Blob Access Point configurations in a Storage Account.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param [Hash] opts the optional parameters
  # @return [BlobAccessPointConfigurationListResult]
  describe 'blob_access_point_configurations_list_by_storage_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blob_access_point_configurations_test_existing_connection
  # Test the connection configured on an existing Blob Access Point configuration.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param blob_access_point_configuration_name The name of the Blob Access Point configuration.
  # @param body The content of the action request
  # @param [Hash] opts the optional parameters
  # @return [BlobAccessPointConnectionTestResponse]
  describe 'blob_access_point_configurations_test_existing_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blob_access_point_configurations_update
  # Update a Blob Access Point configuration.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param blob_access_point_configuration_name The name of the Blob Access Point configuration.
  # @param properties The resource properties to be updated.
  # @param [Hash] opts the optional parameters
  # @return [BlobAccessPointConfiguration]
  describe 'blob_access_point_configurations_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
