=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::FileServiceUsageOperationGroupApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FileServiceUsageOperationGroupApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::FileServiceUsageOperationGroupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileServiceUsageOperationGroupApi' do
    it 'should create an instance of FileServiceUsageOperationGroupApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::FileServiceUsageOperationGroupApi)
    end
  end

  # unit tests for file_services_get_service_usage
  # Gets the usage of file service in storage account including account limits, file share limits and constants used in recommendations and bursting formula.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param [Hash] opts the optional parameters
  # @return [FileServiceUsage]
  describe 'file_services_get_service_usage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_services_list_service_usages
  # Gets the usages of file service in storage account.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :maxpagesize Optional, specifies the maximum number of file service usages to be included in the list response.
  # @return [FileServiceUsages]
  describe 'file_services_list_service_usages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
