=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::LocalUserOperationGroupApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LocalUserOperationGroupApi' do
  before do
    # run before each test
    @api_instance = AzureRest::LocalUserOperationGroupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocalUserOperationGroupApi' do
    it 'should create an instance of LocalUserOperationGroupApi' do
      expect(@api_instance).to be_instance_of(AzureRest::LocalUserOperationGroupApi)
    end
  end

  # unit tests for local_users_create_or_update
  # Create or update the properties of a local user associated with the storage account. Properties for NFSv3 enablement and extended groups cannot be set with other properties.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param username The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
  # @param properties The local user associated with a storage account.
  # @param [Hash] opts the optional parameters
  # @return [LocalUser]
  describe 'local_users_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for local_users_delete
  # Deletes the local user associated with the specified storage account.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param username The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'local_users_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for local_users_get
  # Get the local user of the storage account by username.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param username The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
  # @param [Hash] opts the optional parameters
  # @return [LocalUser]
  describe 'local_users_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for local_users_list
  # List the local users associated with the storage account.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :maxpagesize Optional, specifies the maximum number of local users that will be included in the list response.
  # @option opts [String] :filter Optional. When specified, only local user names starting with the filter will be listed.
  # @option opts [String] :include Optional, when specified, will list local users enabled for the specific protocol. Lists all users by default.
  # @return [LocalUsers]
  describe 'local_users_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for local_users_list_keys
  # List SSH authorized keys and shared key of the local user.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param username The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
  # @param [Hash] opts the optional parameters
  # @return [LocalUserKeys]
  describe 'local_users_list_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for local_users_regenerate_password
  # Regenerate the local user SSH password.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param account_name The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
  # @param username The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
  # @param [Hash] opts the optional parameters
  # @return [LocalUserRegeneratePasswordResult]
  describe 'local_users_regenerate_password test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
