=begin
#SqlManagementClient

#The Azure SQL Database management API provides a RESTful set of web APIs that interact with Azure SQL Database services to manage your databases. The API enables users to create, retrieve, update, and delete databases, servers, and other entities.

The version of the OpenAPI document: 2025-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureRest
  module Sql
  class PrivateLinkServiceConnectionStateStatus
    APPROVED = "Approved".freeze
    PENDING = "Pending".freeze
    REJECTED = "Rejected".freeze
    DISCONNECTED = "Disconnected".freeze

    def self.all_vars
      @all_vars ||= [APPROVED, PENDING, REJECTED, DISCONNECTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrivateLinkServiceConnectionStateStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrivateLinkServiceConnectionStateStatus"
    end
  end
  end
end