=begin
#ResourceManagementClient

#Provides operations for working with resources and resource groups.

The version of the OpenAPI document: 2025-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::ExtendedLocationType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::ExtendedLocationType do
  #let(:instance) { AzureRest::ExtendedLocationType.new }

  describe 'test an instance of ExtendedLocationType' do
    it 'should create an instance of ExtendedLocationType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::ExtendedLocationType)
    end
  end

end
