=begin
#ResourceManagementClient

#Provides operations for working with resources and resource groups.

The version of the OpenAPI document: 2025-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::ResourceGroupPatchable
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::ResourceGroupPatchable do
  #let(:instance) { AzureRest::ResourceGroupPatchable.new }

  describe 'test an instance of ResourceGroupPatchable' do
    it 'should create an instance of ResourceGroupPatchable' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::ResourceGroupPatchable)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "properties"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "managed_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "tags"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
