=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::CustomIpPrefixesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomIpPrefixesApi' do
  before do
    # run before each test
    @api_instance = AzureRest::CustomIpPrefixesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomIpPrefixesApi' do
    it 'should create an instance of CustomIpPrefixesApi' do
      expect(@api_instance).to be_instance_of(AzureRest::CustomIpPrefixesApi)
    end
  end

  # unit tests for custom_ip_prefixes_create_or_update
  # Creates or updates a custom IP prefix.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param custom_ip_prefix_name The name of the custom IP prefix.
  # @param parameters Parameters supplied to the create or update custom IP prefix operation.
  # @param [Hash] opts the optional parameters
  # @return [CustomIpPrefix]
  describe 'custom_ip_prefixes_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_ip_prefixes_delete
  # Deletes the specified custom IP prefix.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param custom_ip_prefix_name The name of the custom IP prefix.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'custom_ip_prefixes_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_ip_prefixes_get
  # Gets the specified custom IP prefix in a specified resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param custom_ip_prefix_name The name of the custom IP prefix.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand Expands referenced resources.
  # @return [CustomIpPrefix]
  describe 'custom_ip_prefixes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_ip_prefixes_list
  # Gets all custom IP prefixes in a resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param [Hash] opts the optional parameters
  # @return [CustomIpPrefixListResult]
  describe 'custom_ip_prefixes_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_ip_prefixes_list_all
  # Gets all the custom IP prefixes in a subscription.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param [Hash] opts the optional parameters
  # @return [CustomIpPrefixListResult]
  describe 'custom_ip_prefixes_list_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_ip_prefixes_update_tags
  # Updates custom IP prefix tags.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param custom_ip_prefix_name The name of the custom IP prefix.
  # @param parameters Parameters supplied to update custom IP prefix tags.
  # @param [Hash] opts the optional parameters
  # @return [CustomIpPrefix]
  describe 'custom_ip_prefixes_update_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
