=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::DdosCustomPoliciesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DdosCustomPoliciesApi' do
  before do
    # run before each test
    @api_instance = AzureRest::DdosCustomPoliciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DdosCustomPoliciesApi' do
    it 'should create an instance of DdosCustomPoliciesApi' do
      expect(@api_instance).to be_instance_of(AzureRest::DdosCustomPoliciesApi)
    end
  end

  # unit tests for ddos_custom_policies_create_or_update
  # Creates or updates a DDoS custom policy.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param ddos_custom_policy_name The name of the DDoS custom policy.
  # @param parameters Parameters supplied to the create or update operation.
  # @param [Hash] opts the optional parameters
  # @return [DdosCustomPolicy]
  describe 'ddos_custom_policies_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ddos_custom_policies_delete
  # Deletes the specified DDoS custom policy.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param ddos_custom_policy_name The name of the DDoS custom policy.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ddos_custom_policies_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ddos_custom_policies_get
  # Gets information about the specified DDoS custom policy.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param ddos_custom_policy_name The name of the DDoS custom policy.
  # @param [Hash] opts the optional parameters
  # @return [DdosCustomPolicy]
  describe 'ddos_custom_policies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ddos_custom_policies_list
  # Gets all the DDoS custom policies in a resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param [Hash] opts the optional parameters
  # @return [DdosCustomPolicyListResult]
  describe 'ddos_custom_policies_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ddos_custom_policies_list_all
  # Gets all the DDoS custom policies in a subscription.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param [Hash] opts the optional parameters
  # @return [DdosCustomPolicyListResult]
  describe 'ddos_custom_policies_list_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ddos_custom_policies_update_tags
  # Update a DDoS custom policy tags.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param ddos_custom_policy_name The name of the DDoS custom policy.
  # @param parameters Parameters supplied to update DDoS custom policy resource tags.
  # @param [Hash] opts the optional parameters
  # @return [DdosCustomPolicy]
  describe 'ddos_custom_policies_update_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
