=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::NetworkSecurityGroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NetworkSecurityGroupsApi' do
  before do
    # run before each test
    @api_instance = AzureRest::NetworkSecurityGroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NetworkSecurityGroupsApi' do
    it 'should create an instance of NetworkSecurityGroupsApi' do
      expect(@api_instance).to be_instance_of(AzureRest::NetworkSecurityGroupsApi)
    end
  end

  # unit tests for network_security_groups_create_or_update
  # Creates or updates a network security group in the specified resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param network_security_group_name The name of the network security group.
  # @param parameters Parameters supplied to the create or update network security group operation.
  # @param [Hash] opts the optional parameters
  # @return [NetworkSecurityGroup]
  describe 'network_security_groups_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for network_security_groups_delete
  # Deletes the specified network security group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param network_security_group_name The name of the network security group.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'network_security_groups_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for network_security_groups_get
  # Gets the specified network security group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param network_security_group_name The name of the network security group.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand Expands referenced resources.
  # @return [NetworkSecurityGroup]
  describe 'network_security_groups_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for network_security_groups_list
  # Gets all network security groups in a resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param [Hash] opts the optional parameters
  # @return [NetworkSecurityGroupListResult]
  describe 'network_security_groups_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for network_security_groups_list_all
  # Gets all network security groups in a subscription.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param [Hash] opts the optional parameters
  # @return [NetworkSecurityGroupListResult]
  describe 'network_security_groups_list_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for network_security_groups_update_tags
  # Updates a network security group tags.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param network_security_group_name The name of the network security group.
  # @param parameters Parameters supplied to update network security group tags.
  # @param [Hash] opts the optional parameters
  # @return [NetworkSecurityGroup]
  describe 'network_security_groups_update_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
