=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::PrivateDnsZoneGroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrivateDnsZoneGroupsApi' do
  before do
    # run before each test
    @api_instance = AzureRest::PrivateDnsZoneGroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrivateDnsZoneGroupsApi' do
    it 'should create an instance of PrivateDnsZoneGroupsApi' do
      expect(@api_instance).to be_instance_of(AzureRest::PrivateDnsZoneGroupsApi)
    end
  end

  # unit tests for private_dns_zone_groups_create_or_update
  # Creates or updates a private dns zone group in the specified private endpoint.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param private_endpoint_name The name of the private endpoint.
  # @param private_dns_zone_group_name The name of the private endpoint.
  # @param parameters Parameters supplied to the create or update private dns zone group operation.
  # @param [Hash] opts the optional parameters
  # @return [PrivateDnsZoneGroup]
  describe 'private_dns_zone_groups_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_dns_zone_groups_delete
  # Deletes the specified private dns zone group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param private_endpoint_name The name of the private endpoint.
  # @param private_dns_zone_group_name The name of the private endpoint.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'private_dns_zone_groups_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_dns_zone_groups_get
  # Gets the private dns zone group resource by specified private dns zone group name.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param private_endpoint_name The name of the private endpoint.
  # @param private_dns_zone_group_name The name of the private endpoint.
  # @param [Hash] opts the optional parameters
  # @return [PrivateDnsZoneGroup]
  describe 'private_dns_zone_groups_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_dns_zone_groups_list
  # Gets all private dns zone groups in a private endpoint.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param private_endpoint_name The name of the private endpoint.
  # @param [Hash] opts the optional parameters
  # @return [PrivateDnsZoneGroupListResult]
  describe 'private_dns_zone_groups_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
