=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::VirtualNetworkPeeringsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VirtualNetworkPeeringsApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::VirtualNetworkPeeringsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VirtualNetworkPeeringsApi' do
    it 'should create an instance of VirtualNetworkPeeringsApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::VirtualNetworkPeeringsApi)
    end
  end

  # unit tests for virtual_network_peerings_create_or_update
  # Creates or updates a peering in the specified virtual network.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param virtual_network_peering_name The name of the virtual network peering.
  # @param virtual_network_peering_parameters Parameters supplied to the create or update virtual network peering operation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sync_remote_address_space Parameter indicates the intention to sync the peering with the current address space on the remote vNet after it&#39;s updated.
  # @return [VirtualNetworkPeering]
  describe 'virtual_network_peerings_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_network_peerings_delete
  # Deletes the specified virtual network peering.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param virtual_network_peering_name The name of the virtual network peering.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_network_peerings_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_network_peerings_get
  # Gets the specified virtual network peering.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param virtual_network_peering_name The name of the virtual network peering.
  # @param [Hash] opts the optional parameters
  # @return [VirtualNetworkPeering]
  describe 'virtual_network_peerings_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_network_peerings_list
  # Gets all virtual network peerings in a virtual network.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param [Hash] opts the optional parameters
  # @return [VirtualNetworkPeeringListResult]
  describe 'virtual_network_peerings_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
