=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::VirtualNetworksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VirtualNetworksApi' do
  before do
    # run before each test
    @api_instance = AzureRest::VirtualNetworksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VirtualNetworksApi' do
    it 'should create an instance of VirtualNetworksApi' do
      expect(@api_instance).to be_instance_of(AzureRest::VirtualNetworksApi)
    end
  end

  # unit tests for virtual_networks_create_or_update
  # Creates or updates a virtual network in the specified resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param parameters Parameters supplied to the create or update virtual network operation.
  # @param [Hash] opts the optional parameters
  # @return [VirtualNetwork]
  describe 'virtual_networks_create_or_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_networks_delete
  # Deletes the specified virtual network.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_networks_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_networks_get
  # Gets the specified virtual network by resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand Expands referenced resources.
  # @return [VirtualNetwork]
  describe 'virtual_networks_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_networks_list
  # Gets all virtual networks in a resource group.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param [Hash] opts the optional parameters
  # @return [VirtualNetworkListResult]
  describe 'virtual_networks_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_networks_list_all
  # Gets all virtual networks in a subscription.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param [Hash] opts the optional parameters
  # @return [VirtualNetworkListResult]
  describe 'virtual_networks_list_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_networks_move_ip_configurations
  # Move IP configurations from one virtual network to another.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param body Parameters supplied to move IP configurations from one virtual network to another.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_networks_move_ip_configurations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_networks_update_tags
  # Updates a virtual network tags.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_network_name The name of the virtual network.
  # @param parameters Parameters supplied to update virtual network tags.
  # @param [Hash] opts the optional parameters
  # @return [VirtualNetwork]
  describe 'virtual_networks_update_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
