=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module Network
  # Properties of the load balancer.
  class LoadBalancerPropertiesFormat < ApiModelBase
    # Object representing the frontend IPs to be used for the load balancer.
    attr_accessor :frontend_ip_configurations

    # Collection of backend address pools used by a load balancer.
    attr_accessor :backend_address_pools

    # Object collection representing the load balancing rules Gets the provisioning.
    attr_accessor :load_balancing_rules

    # Collection of probe objects used in the load balancer.
    attr_accessor :probes

    # Collection of inbound NAT Rules used by a load balancer. Defining inbound NAT rules on your load balancer is mutually exclusive with defining an inbound NAT pool. Inbound NAT pools are referenced from virtual machine scale sets. NICs that are associated with individual virtual machines cannot reference an Inbound NAT pool. They have to reference individual inbound NAT rules.
    attr_accessor :inbound_nat_rules

    # Defines an external port range for inbound NAT to a single backend port on NICs associated with a load balancer. Inbound NAT rules are created automatically for each NIC associated with the Load Balancer using an external port from this range. Defining an Inbound NAT pool on your Load Balancer is mutually exclusive with defining inbound NAT rules. Inbound NAT pools are referenced from virtual machine scale sets. NICs that are associated with individual virtual machines cannot reference an inbound NAT pool. They have to reference individual inbound NAT rules.
    attr_accessor :inbound_nat_pools

    # The outbound rules.
    attr_accessor :outbound_rules

    # The resource GUID property of the load balancer resource.
    attr_accessor :resource_guid

    attr_accessor :provisioning_state

    attr_accessor :scope

    attr_accessor :mode

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'frontend_ip_configurations' => :'frontendIPConfigurations',
        :'backend_address_pools' => :'backendAddressPools',
        :'load_balancing_rules' => :'loadBalancingRules',
        :'probes' => :'probes',
        :'inbound_nat_rules' => :'inboundNatRules',
        :'inbound_nat_pools' => :'inboundNatPools',
        :'outbound_rules' => :'outboundRules',
        :'resource_guid' => :'resourceGuid',
        :'provisioning_state' => :'provisioningState',
        :'scope' => :'scope',
        :'mode' => :'mode'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'frontend_ip_configurations' => :'Array<FrontendIPConfiguration>',
        :'backend_address_pools' => :'Array<BackendAddressPool>',
        :'load_balancing_rules' => :'Array<LoadBalancingRule>',
        :'probes' => :'Array<Probe>',
        :'inbound_nat_rules' => :'Array<InboundNatRule>',
        :'inbound_nat_pools' => :'Array<InboundNatPool>',
        :'outbound_rules' => :'Array<OutboundRule>',
        :'resource_guid' => :'String',
        :'provisioning_state' => :'ProvisioningState',
        :'scope' => :'LoadBalancerScope',
        :'mode' => :'LoadBalancerMode'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AzureRest::LoadBalancerPropertiesFormat` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AzureRest::LoadBalancerPropertiesFormat`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'frontend_ip_configurations')
        if (value = attributes[:'frontend_ip_configurations']).is_a?(Array)
          self.frontend_ip_configurations = value
        end
      end

      if attributes.key?(:'backend_address_pools')
        if (value = attributes[:'backend_address_pools']).is_a?(Array)
          self.backend_address_pools = value
        end
      end

      if attributes.key?(:'load_balancing_rules')
        if (value = attributes[:'load_balancing_rules']).is_a?(Array)
          self.load_balancing_rules = value
        end
      end

      if attributes.key?(:'probes')
        if (value = attributes[:'probes']).is_a?(Array)
          self.probes = value
        end
      end

      if attributes.key?(:'inbound_nat_rules')
        if (value = attributes[:'inbound_nat_rules']).is_a?(Array)
          self.inbound_nat_rules = value
        end
      end

      if attributes.key?(:'inbound_nat_pools')
        if (value = attributes[:'inbound_nat_pools']).is_a?(Array)
          self.inbound_nat_pools = value
        end
      end

      if attributes.key?(:'outbound_rules')
        if (value = attributes[:'outbound_rules']).is_a?(Array)
          self.outbound_rules = value
        end
      end

      if attributes.key?(:'resource_guid')
        self.resource_guid = attributes[:'resource_guid']
      end

      if attributes.key?(:'provisioning_state')
        self.provisioning_state = attributes[:'provisioning_state']
      end

      if attributes.key?(:'scope')
        self.scope = attributes[:'scope']
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          frontend_ip_configurations == o.frontend_ip_configurations &&
          backend_address_pools == o.backend_address_pools &&
          load_balancing_rules == o.load_balancing_rules &&
          probes == o.probes &&
          inbound_nat_rules == o.inbound_nat_rules &&
          inbound_nat_pools == o.inbound_nat_pools &&
          outbound_rules == o.outbound_rules &&
          resource_guid == o.resource_guid &&
          provisioning_state == o.provisioning_state &&
          scope == o.scope &&
          mode == o.mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [frontend_ip_configurations, backend_address_pools, load_balancing_rules, probes, inbound_nat_rules, inbound_nat_pools, outbound_rules, resource_guid, provisioning_state, scope, mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

  end
end