=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module Network
  class SecurityPartnerProviderConnectionStatus
    UNKNOWN = "Unknown".freeze
    PARTIALLY_CONNECTED = "PartiallyConnected".freeze
    CONNECTED = "Connected".freeze
    NOT_CONNECTED = "NotConnected".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, PARTIALLY_CONNECTED, CONNECTED, NOT_CONNECTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SecurityPartnerProviderConnectionStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SecurityPartnerProviderConnectionStatus"
    end
  end
  end
end