=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module Network
  class SharingScope
    TENANT = "Tenant".freeze
    DELEGATED_SERVICES = "DelegatedServices".freeze

    def self.all_vars
      @all_vars ||= [TENANT, DELEGATED_SERVICES].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SharingScope.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SharingScope"
    end
  end
  end
end