=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module Network
  # Virtual Network Tap properties.
  class VirtualNetworkTapPropertiesFormat < ApiModelBase
    # Specifies the list of resource IDs for the network interface IP configuration that needs to be tapped.
    attr_accessor :network_interface_tap_configurations

    # The resource GUID property of the virtual network tap resource.
    attr_accessor :resource_guid

    attr_accessor :provisioning_state

    attr_accessor :destination_network_interface_ip_configuration

    attr_accessor :destination_load_balancer_front_end_ip_configuration

    # The VXLAN destination port that will receive the tapped traffic.
    attr_accessor :destination_port

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'network_interface_tap_configurations' => :'networkInterfaceTapConfigurations',
        :'resource_guid' => :'resourceGuid',
        :'provisioning_state' => :'provisioningState',
        :'destination_network_interface_ip_configuration' => :'destinationNetworkInterfaceIPConfiguration',
        :'destination_load_balancer_front_end_ip_configuration' => :'destinationLoadBalancerFrontEndIPConfiguration',
        :'destination_port' => :'destinationPort'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'network_interface_tap_configurations' => :'Array<NetworkInterfaceTapConfiguration2>',
        :'resource_guid' => :'String',
        :'provisioning_state' => :'ProvisioningState',
        :'destination_network_interface_ip_configuration' => :'NetworkInterfaceIPConfiguration2',
        :'destination_load_balancer_front_end_ip_configuration' => :'FrontendIPConfiguration',
        :'destination_port' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AzureRest::VirtualNetworkTapPropertiesFormat` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AzureRest::VirtualNetworkTapPropertiesFormat`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'network_interface_tap_configurations')
        if (value = attributes[:'network_interface_tap_configurations']).is_a?(Array)
          self.network_interface_tap_configurations = value
        end
      end

      if attributes.key?(:'resource_guid')
        self.resource_guid = attributes[:'resource_guid']
      end

      if attributes.key?(:'provisioning_state')
        self.provisioning_state = attributes[:'provisioning_state']
      end

      if attributes.key?(:'destination_network_interface_ip_configuration')
        self.destination_network_interface_ip_configuration = attributes[:'destination_network_interface_ip_configuration']
      end

      if attributes.key?(:'destination_load_balancer_front_end_ip_configuration')
        self.destination_load_balancer_front_end_ip_configuration = attributes[:'destination_load_balancer_front_end_ip_configuration']
      end

      if attributes.key?(:'destination_port')
        self.destination_port = attributes[:'destination_port']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          network_interface_tap_configurations == o.network_interface_tap_configurations &&
          resource_guid == o.resource_guid &&
          provisioning_state == o.provisioning_state &&
          destination_network_interface_ip_configuration == o.destination_network_interface_ip_configuration &&
          destination_load_balancer_front_end_ip_configuration == o.destination_load_balancer_front_end_ip_configuration &&
          destination_port == o.destination_port
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [network_interface_tap_configurations, resource_guid, provisioning_state, destination_network_interface_ip_configuration, destination_load_balancer_front_end_ip_configuration, destination_port].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

  end
end