=begin
#MySQLManagementClient

#The Microsoft Azure management API provides create, read, update, and delete functionality for Azure MySQL resources including servers, databases, firewall rules, VNET rules, log files and configurations with new business model.

The version of the OpenAPI document: 2024-12-30

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::ObjectType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::ObjectType do
  #let(:instance) { AzureRest::ObjectType.new }

  describe 'test an instance of ObjectType' do
    it 'should create an instance of ObjectType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::ObjectType)
    end
  end

end
