=begin
#MySQLManagementClient

#The Microsoft Azure management API provides create, read, update, and delete functionality for Azure MySQL resources including servers, databases, firewall rules, VNET rules, log files and configurations with new business model.

The version of the OpenAPI document: 2024-12-30

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::SystemData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::SystemData do
  #let(:instance) { AzureRest::SystemData.new }

  describe 'test an instance of SystemData' do
    it 'should create an instance of SystemData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::SystemData)
    end
  end

  describe 'test attribute "created_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_by_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["User", "Application", "ManagedIdentity", "Key"])
      # validator.allowable_values.each do |value|
      #   expect { instance.created_by_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_modified_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_modified_by_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["User", "Application", "ManagedIdentity", "Key"])
      # validator.allowable_values.each do |value|
      #   expect { instance.last_modified_by_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "last_modified_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
