=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureSDK
  module Storage
  # The replication policy rule between two containers.
  class ObjectReplicationPolicyRule < ApiModelBase
    # Rule Id is auto-generated for each new rule on destination account. It is required for put policy on source account.
    attr_accessor :rule_id

    # Required. Source container name.
    attr_accessor :source_container

    # Required. Destination container name.
    attr_accessor :destination_container

    attr_accessor :filters

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rule_id' => :'ruleId',
        :'source_container' => :'sourceContainer',
        :'destination_container' => :'destinationContainer',
        :'filters' => :'filters'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rule_id' => :'String',
        :'source_container' => :'String',
        :'destination_container' => :'String',
        :'filters' => :'ObjectReplicationPolicyFilter'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AzureSDK::ObjectReplicationPolicyRule` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AzureSDK::ObjectReplicationPolicyRule`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rule_id')
        self.rule_id = attributes[:'rule_id']
      end

      if attributes.key?(:'source_container')
        self.source_container = attributes[:'source_container']
      else
        self.source_container = nil
      end

      if attributes.key?(:'destination_container')
        self.destination_container = attributes[:'destination_container']
      else
        self.destination_container = nil
      end

      if attributes.key?(:'filters')
        self.filters = attributes[:'filters']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @source_container.nil?
        invalid_properties.push('invalid value for "source_container", source_container cannot be nil.')
      end

      if @destination_container.nil?
        invalid_properties.push('invalid value for "destination_container", destination_container cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @source_container.nil?
      return false if @destination_container.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] source_container Value to be assigned
    def source_container=(source_container)
      if source_container.nil?
        fail ArgumentError, 'source_container cannot be nil'
      end

      @source_container = source_container
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_container Value to be assigned
    def destination_container=(destination_container)
      if destination_container.nil?
        fail ArgumentError, 'destination_container cannot be nil'
      end

      @destination_container = destination_container
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rule_id == o.rule_id &&
          source_container == o.source_container &&
          destination_container == o.destination_container &&
          filters == o.filters
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rule_id, source_container, destination_container, filters].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

  end
end