=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureSDK
  module Storage
  class Reason
    ACCOUNT_NAME_INVALID = "AccountNameInvalid".freeze
    ALREADY_EXISTS = "AlreadyExists".freeze

    def self.all_vars
      @all_vars ||= [ACCOUNT_NAME_INVALID, ALREADY_EXISTS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Reason.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Reason"
    end
  end
  end
end