=begin
#SqlManagementClient

#The Azure SQL Database management API provides a RESTful set of web APIs that interact with Azure SQL Database services to manage your databases. The API enables users to create, retrieve, update, and delete databases, servers, and other entities.

The version of the OpenAPI document: 2025-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::ServerPublicNetworkAccessFlag
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::ServerPublicNetworkAccessFlag do
  #let(:instance) { AzureRest::ServerPublicNetworkAccessFlag.new }

  describe 'test an instance of ServerPublicNetworkAccessFlag' do
    it 'should create an instance of ServerPublicNetworkAccessFlag' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::ServerPublicNetworkAccessFlag)
    end
  end

end
