=begin
#ContainerServiceClient

#The Container Service Client.

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::DRANETMode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::DRANETMode do
  #let(:instance) { AzureSDK::DRANETMode.new }

  describe 'test an instance of DRANETMode' do
    it 'should create an instance of DRANETMode' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::DRANETMode)
    end
  end

end
