=begin
#ContainerServiceClient

#The Container Service Client.

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::ManagedClusterMetricsProfile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::ManagedClusterMetricsProfile do
  #let(:instance) { AzureSDK::ManagedClusterMetricsProfile.new }

  describe 'test an instance of ManagedClusterMetricsProfile' do
    it 'should create an instance of ManagedClusterMetricsProfile' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::ManagedClusterMetricsProfile)
    end
  end

  describe 'test attribute "cost_analysis"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
