=begin
#ContainerServiceClient

#The Container Service Client.

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::ManagedClusterAzureMonitorProfileContainerInsights
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::ManagedClusterAzureMonitorProfileContainerInsights do
  #let(:instance) { AzureSDK::ManagedClusterAzureMonitorProfileContainerInsights.new }

  describe 'test an instance of ManagedClusterAzureMonitorProfileContainerInsights' do
    it 'should create an instance of ManagedClusterAzureMonitorProfileContainerInsights' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::ManagedClusterAzureMonitorProfileContainerInsights)
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "log_analytics_workspace_resource_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "syslog_port"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "disable_prometheus_metrics_scraping"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "container_network_logs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
