=begin
#ContainerServiceClient

#The Container Service Client.

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::ManagedClusterNATGatewayProfileOutboundIPs
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::ManagedClusterNATGatewayProfileOutboundIPs do
  #let(:instance) { AzureRest::ManagedClusterNATGatewayProfileOutboundIPs.new }

  describe 'test an instance of ManagedClusterNATGatewayProfileOutboundIPs' do
    it 'should create an instance of ManagedClusterNATGatewayProfileOutboundIPs' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::ManagedClusterNATGatewayProfileOutboundIPs)
    end
  end

  describe 'test attribute "public_ips"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
