=begin
#ContainerServiceClient

#The Container Service Client.

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::WindowsGmsaProfile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::WindowsGmsaProfile do
  #let(:instance) { AzureRest::WindowsGmsaProfile.new }

  describe 'test an instance of WindowsGmsaProfile' do
    it 'should create an instance of WindowsGmsaProfile' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::WindowsGmsaProfile)
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "dns_server"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "root_domain_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
