=begin
#StorageManagementClient

#The Azure Storage Management API.

The version of the OpenAPI document: 2026-09-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureRest
  module Storage
  class BlobRestoreProgressStatus
    IN_PROGRESS = "InProgress".freeze
    COMPLETE = "Complete".freeze
    FAILED = "Failed".freeze

    def self.all_vars
      @all_vars ||= [IN_PROGRESS, COMPLETE, FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BlobRestoreProgressStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BlobRestoreProgressStatus"
    end
  end
  end
end