=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::AttachDetachDataDisksRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::AttachDetachDataDisksRequest do
  #let(:instance) { AzureRest::AttachDetachDataDisksRequest.new }

  describe 'test an instance of AttachDetachDataDisksRequest' do
    it 'should create an instance of AttachDetachDataDisksRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::AttachDetachDataDisksRequest)
    end
  end

  describe 'test attribute "data_disks_to_attach"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_disks_to_detach"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
