=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::AutomaticOSUpgradePolicy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::AutomaticOSUpgradePolicy do
  #let(:instance) { AzureRest::AutomaticOSUpgradePolicy.new }

  describe 'test an instance of AutomaticOSUpgradePolicy' do
    it 'should create an instance of AutomaticOSUpgradePolicy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::AutomaticOSUpgradePolicy)
    end
  end

  describe 'test attribute "enable_automatic_os_upgrade"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "disable_automatic_rollback"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "use_rolling_upgrade_policy"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "os_rolling_upgrade_deferral"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
