=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::DiffDiskPlacement
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::DiffDiskPlacement do
  #let(:instance) { AzureSDK::DiffDiskPlacement.new }

  describe 'test an instance of DiffDiskPlacement' do
    it 'should create an instance of DiffDiskPlacement' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::DiffDiskPlacement)
    end
  end

end
