=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::DiskAvailabilityPolicy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::DiskAvailabilityPolicy do
  #let(:instance) { AzureRest::DiskAvailabilityPolicy.new }

  describe 'test an instance of DiskAvailabilityPolicy' do
    it 'should create an instance of DiskAvailabilityPolicy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::DiskAvailabilityPolicy)
    end
  end

  describe 'test attribute "action_on_disk_delay"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
