=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::HyperVGenerationType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::HyperVGenerationType do
  #let(:instance) { AzureRest::HyperVGenerationType.new }

  describe 'test an instance of HyperVGenerationType' do
    it 'should create an instance of HyperVGenerationType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::HyperVGenerationType)
    end
  end

end
