=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::PriorityMixPolicy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::PriorityMixPolicy do
  #let(:instance) { AzureSDK::PriorityMixPolicy.new }

  describe 'test an instance of PriorityMixPolicy' do
    it 'should create an instance of PriorityMixPolicy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::PriorityMixPolicy)
    end
  end

  describe 'test attribute "base_regular_priority_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "regular_priority_percentage_above_base"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
