=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::VirtualMachineScaleSetStorageProfile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::VirtualMachineScaleSetStorageProfile do
  #let(:instance) { AzureRest::VirtualMachineScaleSetStorageProfile.new }

  describe 'test an instance of VirtualMachineScaleSetStorageProfile' do
    it 'should create an instance of VirtualMachineScaleSetStorageProfile' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::VirtualMachineScaleSetStorageProfile)
    end
  end

  describe 'test attribute "image_reference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "os_disk"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_disks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "disk_controller_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "disk_api_version"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
