=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::VirtualMachineScaleSetUpdateNetworkProfile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::VirtualMachineScaleSetUpdateNetworkProfile do
  #let(:instance) { AzureRest::VirtualMachineScaleSetUpdateNetworkProfile.new }

  describe 'test an instance of VirtualMachineScaleSetUpdateNetworkProfile' do
    it 'should create an instance of VirtualMachineScaleSetUpdateNetworkProfile' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::VirtualMachineScaleSetUpdateNetworkProfile)
    end
  end

  describe 'test attribute "health_probe"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "network_interface_configurations"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "network_api_version"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "interconnect_group_profile"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
