=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::VMScaleSetConvertToSinglePlacementGroupInput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::VMScaleSetConvertToSinglePlacementGroupInput do
  #let(:instance) { AzureSDK::VMScaleSetConvertToSinglePlacementGroupInput.new }

  describe 'test an instance of VMScaleSetConvertToSinglePlacementGroupInput' do
    it 'should create an instance of VMScaleSetConvertToSinglePlacementGroupInput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::VMScaleSetConvertToSinglePlacementGroupInput)
    end
  end

  describe 'test attribute "active_placement_group_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
