=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::VMScaleSetLifecycleHookEventState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::VMScaleSetLifecycleHookEventState do
  #let(:instance) { AzureSDK::VMScaleSetLifecycleHookEventState.new }

  describe 'test an instance of VMScaleSetLifecycleHookEventState' do
    it 'should create an instance of VMScaleSetLifecycleHookEventState' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::VMScaleSetLifecycleHookEventState)
    end
  end

end
