=begin
#KeyVaultManagementClient

#The Azure management API provides a RESTful set of web services that interact with Azure Key Vault.

The version of the OpenAPI document: 2026-05-15

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureSDK
  module KeyVault
  class SecretPermissions
    ALL = "all".freeze
    GET = "get".freeze
    LIST = "list".freeze
    SET = "set".freeze
    DELETE = "delete".freeze
    BACKUP = "backup".freeze
    RESTORE = "restore".freeze
    RECOVER = "recover".freeze
    PURGE = "purge".freeze

    def self.all_vars
      @all_vars ||= [ALL, GET, LIST, SET, DELETE, BACKUP, RESTORE, RECOVER, PURGE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SecretPermissions.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SecretPermissions"
    end
  end
  end
end