=begin
#PostgreSQLManagementClient

#The Azure Database for PostgreSQL management API provides create, read, update, and delete functionality for Azure PostgreSQL resources including servers, databases, firewall rules, network configuration, security alert policies, log files and configurations with new business model.

The version of the OpenAPI document: 2025-08-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module AzureSDK
  module PostgreSQL
  # Properties of a server.
  class ServerProperties < ApiModelBase
    # Name of the login designated as the first password based administrator assigned to your instance of PostgreSQL. Must be specified the first time that you enable password based authentication on a server. Once set to a given value, it cannot be changed for the rest of the life of a server. If you disable password based authentication on a server which had it enabled, this password based role isn't deleted.
    attr_accessor :administrator_login

    # Password assigned to the administrator login. As long as password authentication is enabled, this password can be changed at any time.
    attr_accessor :administrator_login_password

    attr_accessor :version

    # Minor version of PostgreSQL database engine.
    attr_accessor :minor_version

    attr_accessor :state

    # Fully qualified domain name of a server.
    attr_accessor :fully_qualified_domain_name

    attr_accessor :storage

    attr_accessor :auth_config

    attr_accessor :data_encryption

    attr_accessor :backup

    attr_accessor :network

    attr_accessor :high_availability

    attr_accessor :maintenance_window

    # Identifier of the server to be used as the source of the new server. Required when 'createMode' is 'PointInTimeRestore', 'GeoRestore', 'Replica', or 'ReviveDropped'. This property is returned only when the target server is a read replica.
    attr_accessor :source_server_resource_id

    # Creation time (in ISO8601 format) of the backup which you want to restore in the new server. It's required when 'createMode' is 'PointInTimeRestore', 'GeoRestore', or 'ReviveDropped'.
    attr_accessor :point_in_time_utc

    # Availability zone of a server.
    attr_accessor :availability_zone

    attr_accessor :replication_role

    # Maximum number of read replicas allowed for a server.
    attr_accessor :replica_capacity

    attr_accessor :replica

    attr_accessor :create_mode

    # List of private endpoint connections associated with the specified server.
    attr_accessor :private_endpoint_connections

    attr_accessor :cluster

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'administrator_login' => :'administratorLogin',
        :'administrator_login_password' => :'administratorLoginPassword',
        :'version' => :'version',
        :'minor_version' => :'minorVersion',
        :'state' => :'state',
        :'fully_qualified_domain_name' => :'fullyQualifiedDomainName',
        :'storage' => :'storage',
        :'auth_config' => :'authConfig',
        :'data_encryption' => :'dataEncryption',
        :'backup' => :'backup',
        :'network' => :'network',
        :'high_availability' => :'highAvailability',
        :'maintenance_window' => :'maintenanceWindow',
        :'source_server_resource_id' => :'sourceServerResourceId',
        :'point_in_time_utc' => :'pointInTimeUTC',
        :'availability_zone' => :'availabilityZone',
        :'replication_role' => :'replicationRole',
        :'replica_capacity' => :'replicaCapacity',
        :'replica' => :'replica',
        :'create_mode' => :'createMode',
        :'private_endpoint_connections' => :'privateEndpointConnections',
        :'cluster' => :'cluster'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'administrator_login' => :'String',
        :'administrator_login_password' => :'String',
        :'version' => :'PostgresMajorVersion',
        :'minor_version' => :'String',
        :'state' => :'ServerState',
        :'fully_qualified_domain_name' => :'String',
        :'storage' => :'Storage',
        :'auth_config' => :'AuthConfig',
        :'data_encryption' => :'DataEncryption',
        :'backup' => :'Backup',
        :'network' => :'Network',
        :'high_availability' => :'HighAvailability',
        :'maintenance_window' => :'MaintenanceWindow',
        :'source_server_resource_id' => :'String',
        :'point_in_time_utc' => :'Time',
        :'availability_zone' => :'String',
        :'replication_role' => :'ReplicationRole',
        :'replica_capacity' => :'Integer',
        :'replica' => :'Replica',
        :'create_mode' => :'CreateMode',
        :'private_endpoint_connections' => :'Array<PrivateEndpointConnection>',
        :'cluster' => :'Cluster'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AzureSDK::ServerProperties` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AzureSDK::ServerProperties`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'administrator_login')
        self.administrator_login = attributes[:'administrator_login']
      end

      if attributes.key?(:'administrator_login_password')
        self.administrator_login_password = attributes[:'administrator_login_password']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end

      if attributes.key?(:'minor_version')
        self.minor_version = attributes[:'minor_version']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'fully_qualified_domain_name')
        self.fully_qualified_domain_name = attributes[:'fully_qualified_domain_name']
      end

      if attributes.key?(:'storage')
        self.storage = attributes[:'storage']
      end

      if attributes.key?(:'auth_config')
        self.auth_config = attributes[:'auth_config']
      end

      if attributes.key?(:'data_encryption')
        self.data_encryption = attributes[:'data_encryption']
      end

      if attributes.key?(:'backup')
        self.backup = attributes[:'backup']
      end

      if attributes.key?(:'network')
        self.network = attributes[:'network']
      end

      if attributes.key?(:'high_availability')
        self.high_availability = attributes[:'high_availability']
      end

      if attributes.key?(:'maintenance_window')
        self.maintenance_window = attributes[:'maintenance_window']
      end

      if attributes.key?(:'source_server_resource_id')
        self.source_server_resource_id = attributes[:'source_server_resource_id']
      end

      if attributes.key?(:'point_in_time_utc')
        self.point_in_time_utc = attributes[:'point_in_time_utc']
      end

      if attributes.key?(:'availability_zone')
        self.availability_zone = attributes[:'availability_zone']
      else
        self.availability_zone = ''
      end

      if attributes.key?(:'replication_role')
        self.replication_role = attributes[:'replication_role']
      end

      if attributes.key?(:'replica_capacity')
        self.replica_capacity = attributes[:'replica_capacity']
      end

      if attributes.key?(:'replica')
        self.replica = attributes[:'replica']
      end

      if attributes.key?(:'create_mode')
        self.create_mode = attributes[:'create_mode']
      end

      if attributes.key?(:'private_endpoint_connections')
        if (value = attributes[:'private_endpoint_connections']).is_a?(Array)
          self.private_endpoint_connections = value
        end
      end

      if attributes.key?(:'cluster')
        self.cluster = attributes[:'cluster']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          administrator_login == o.administrator_login &&
          administrator_login_password == o.administrator_login_password &&
          version == o.version &&
          minor_version == o.minor_version &&
          state == o.state &&
          fully_qualified_domain_name == o.fully_qualified_domain_name &&
          storage == o.storage &&
          auth_config == o.auth_config &&
          data_encryption == o.data_encryption &&
          backup == o.backup &&
          network == o.network &&
          high_availability == o.high_availability &&
          maintenance_window == o.maintenance_window &&
          source_server_resource_id == o.source_server_resource_id &&
          point_in_time_utc == o.point_in_time_utc &&
          availability_zone == o.availability_zone &&
          replication_role == o.replication_role &&
          replica_capacity == o.replica_capacity &&
          replica == o.replica &&
          create_mode == o.create_mode &&
          private_endpoint_connections == o.private_endpoint_connections &&
          cluster == o.cluster
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [administrator_login, administrator_login_password, version, minor_version, state, fully_qualified_domain_name, storage, auth_config, data_encryption, backup, network, high_availability, maintenance_window, source_server_resource_id, point_in_time_utc, availability_zone, replication_role, replica_capacity, replica, create_mode, private_endpoint_connections, cluster].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

  end
end