=begin
#HDInsightManagementClient

#The HDInsight Management Client.

The version of the OpenAPI document: 2021-06-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module HDInsight
  # The properties of cluster.
  class ClusterGetProperties < ApiModelBase
    # The version of the cluster.
    attr_accessor :cluster_version

    # The hdp version of the cluster.
    attr_accessor :cluster_hdp_version

    # The type of operating system.
    attr_accessor :os_type

    # The cluster tier.
    attr_accessor :tier

    # The cluster id.
    attr_accessor :cluster_id

    attr_accessor :cluster_definition

    attr_accessor :kafka_rest_properties

    attr_accessor :security_profile

    attr_accessor :compute_profile

    # The provisioning state, which only appears in the response.
    attr_accessor :provisioning_state

    # The date on which the cluster was created.
    attr_accessor :created_date

    # The state of the cluster.
    attr_accessor :cluster_state

    attr_accessor :quota_info

    # The list of errors.
    attr_accessor :errors

    # The list of connectivity endpoints.
    attr_accessor :connectivity_endpoints

    attr_accessor :disk_encryption_properties

    attr_accessor :encryption_in_transit_properties

    attr_accessor :storage_profile

    # The minimal supported tls version.
    attr_accessor :min_supported_tls_version

    attr_accessor :excluded_services_config

    attr_accessor :network_properties

    attr_accessor :compute_isolation_properties

    # The private link configurations.
    attr_accessor :private_link_configurations

    # The list of private endpoint connections.
    attr_accessor :private_endpoint_connections

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cluster_version' => :'clusterVersion',
        :'cluster_hdp_version' => :'clusterHdpVersion',
        :'os_type' => :'osType',
        :'tier' => :'tier',
        :'cluster_id' => :'clusterId',
        :'cluster_definition' => :'clusterDefinition',
        :'kafka_rest_properties' => :'kafkaRestProperties',
        :'security_profile' => :'securityProfile',
        :'compute_profile' => :'computeProfile',
        :'provisioning_state' => :'provisioningState',
        :'created_date' => :'createdDate',
        :'cluster_state' => :'clusterState',
        :'quota_info' => :'quotaInfo',
        :'errors' => :'errors',
        :'connectivity_endpoints' => :'connectivityEndpoints',
        :'disk_encryption_properties' => :'diskEncryptionProperties',
        :'encryption_in_transit_properties' => :'encryptionInTransitProperties',
        :'storage_profile' => :'storageProfile',
        :'min_supported_tls_version' => :'minSupportedTlsVersion',
        :'excluded_services_config' => :'excludedServicesConfig',
        :'network_properties' => :'networkProperties',
        :'compute_isolation_properties' => :'computeIsolationProperties',
        :'private_link_configurations' => :'privateLinkConfigurations',
        :'private_endpoint_connections' => :'privateEndpointConnections'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cluster_version' => :'String',
        :'cluster_hdp_version' => :'String',
        :'os_type' => :'String',
        :'tier' => :'String',
        :'cluster_id' => :'String',
        :'cluster_definition' => :'ClusterDefinition',
        :'kafka_rest_properties' => :'KafkaRestProperties',
        :'security_profile' => :'SecurityProfile',
        :'compute_profile' => :'ComputeProfile',
        :'provisioning_state' => :'String',
        :'created_date' => :'String',
        :'cluster_state' => :'String',
        :'quota_info' => :'QuotaInfo',
        :'errors' => :'Array<Errors>',
        :'connectivity_endpoints' => :'Array<ConnectivityEndpoint>',
        :'disk_encryption_properties' => :'DiskEncryptionProperties',
        :'encryption_in_transit_properties' => :'EncryptionInTransitProperties',
        :'storage_profile' => :'StorageProfile',
        :'min_supported_tls_version' => :'String',
        :'excluded_services_config' => :'ExcludedServicesConfig',
        :'network_properties' => :'NetworkProperties',
        :'compute_isolation_properties' => :'ComputeIsolationProperties',
        :'private_link_configurations' => :'Array<PrivateLinkConfiguration>',
        :'private_endpoint_connections' => :'Array<PrivateEndpointConnection>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AzureRest::ClusterGetProperties` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AzureRest::ClusterGetProperties`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cluster_version')
        self.cluster_version = attributes[:'cluster_version']
      end

      if attributes.key?(:'cluster_hdp_version')
        self.cluster_hdp_version = attributes[:'cluster_hdp_version']
      end

      if attributes.key?(:'os_type')
        self.os_type = attributes[:'os_type']
      end

      if attributes.key?(:'tier')
        self.tier = attributes[:'tier']
      end

      if attributes.key?(:'cluster_id')
        self.cluster_id = attributes[:'cluster_id']
      end

      if attributes.key?(:'cluster_definition')
        self.cluster_definition = attributes[:'cluster_definition']
      else
        self.cluster_definition = nil
      end

      if attributes.key?(:'kafka_rest_properties')
        self.kafka_rest_properties = attributes[:'kafka_rest_properties']
      end

      if attributes.key?(:'security_profile')
        self.security_profile = attributes[:'security_profile']
      end

      if attributes.key?(:'compute_profile')
        self.compute_profile = attributes[:'compute_profile']
      end

      if attributes.key?(:'provisioning_state')
        self.provisioning_state = attributes[:'provisioning_state']
      end

      if attributes.key?(:'created_date')
        self.created_date = attributes[:'created_date']
      end

      if attributes.key?(:'cluster_state')
        self.cluster_state = attributes[:'cluster_state']
      end

      if attributes.key?(:'quota_info')
        self.quota_info = attributes[:'quota_info']
      end

      if attributes.key?(:'errors')
        if (value = attributes[:'errors']).is_a?(Array)
          self.errors = value
        end
      end

      if attributes.key?(:'connectivity_endpoints')
        if (value = attributes[:'connectivity_endpoints']).is_a?(Array)
          self.connectivity_endpoints = value
        end
      end

      if attributes.key?(:'disk_encryption_properties')
        self.disk_encryption_properties = attributes[:'disk_encryption_properties']
      end

      if attributes.key?(:'encryption_in_transit_properties')
        self.encryption_in_transit_properties = attributes[:'encryption_in_transit_properties']
      end

      if attributes.key?(:'storage_profile')
        self.storage_profile = attributes[:'storage_profile']
      end

      if attributes.key?(:'min_supported_tls_version')
        self.min_supported_tls_version = attributes[:'min_supported_tls_version']
      end

      if attributes.key?(:'excluded_services_config')
        self.excluded_services_config = attributes[:'excluded_services_config']
      end

      if attributes.key?(:'network_properties')
        self.network_properties = attributes[:'network_properties']
      end

      if attributes.key?(:'compute_isolation_properties')
        self.compute_isolation_properties = attributes[:'compute_isolation_properties']
      end

      if attributes.key?(:'private_link_configurations')
        if (value = attributes[:'private_link_configurations']).is_a?(Array)
          self.private_link_configurations = value
        end
      end

      if attributes.key?(:'private_endpoint_connections')
        if (value = attributes[:'private_endpoint_connections']).is_a?(Array)
          self.private_endpoint_connections = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @cluster_definition.nil?
        invalid_properties.push('invalid value for "cluster_definition", cluster_definition cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      os_type_validator = EnumAttributeValidator.new('String', ["Windows", "Linux"])
      return false unless os_type_validator.valid?(@os_type)
      tier_validator = EnumAttributeValidator.new('String', ["Standard", "Premium"])
      return false unless tier_validator.valid?(@tier)
      return false if @cluster_definition.nil?
      provisioning_state_validator = EnumAttributeValidator.new('String', ["InProgress", "Failed", "Succeeded", "Canceled", "Deleting"])
      return false unless provisioning_state_validator.valid?(@provisioning_state)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] os_type Object to be assigned
    def os_type=(os_type)
      validator = EnumAttributeValidator.new('String', ["Windows", "Linux"])
      unless validator.valid?(os_type)
        fail ArgumentError, "invalid value for \"os_type\", must be one of #{validator.allowable_values}."
      end
      @os_type = os_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tier Object to be assigned
    def tier=(tier)
      validator = EnumAttributeValidator.new('String', ["Standard", "Premium"])
      unless validator.valid?(tier)
        fail ArgumentError, "invalid value for \"tier\", must be one of #{validator.allowable_values}."
      end
      @tier = tier
    end

    # Custom attribute writer method with validation
    # @param [Object] cluster_definition Value to be assigned
    def cluster_definition=(cluster_definition)
      if cluster_definition.nil?
        fail ArgumentError, 'cluster_definition cannot be nil'
      end

      @cluster_definition = cluster_definition
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] provisioning_state Object to be assigned
    def provisioning_state=(provisioning_state)
      validator = EnumAttributeValidator.new('String', ["InProgress", "Failed", "Succeeded", "Canceled", "Deleting"])
      unless validator.valid?(provisioning_state)
        fail ArgumentError, "invalid value for \"provisioning_state\", must be one of #{validator.allowable_values}."
      end
      @provisioning_state = provisioning_state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cluster_version == o.cluster_version &&
          cluster_hdp_version == o.cluster_hdp_version &&
          os_type == o.os_type &&
          tier == o.tier &&
          cluster_id == o.cluster_id &&
          cluster_definition == o.cluster_definition &&
          kafka_rest_properties == o.kafka_rest_properties &&
          security_profile == o.security_profile &&
          compute_profile == o.compute_profile &&
          provisioning_state == o.provisioning_state &&
          created_date == o.created_date &&
          cluster_state == o.cluster_state &&
          quota_info == o.quota_info &&
          errors == o.errors &&
          connectivity_endpoints == o.connectivity_endpoints &&
          disk_encryption_properties == o.disk_encryption_properties &&
          encryption_in_transit_properties == o.encryption_in_transit_properties &&
          storage_profile == o.storage_profile &&
          min_supported_tls_version == o.min_supported_tls_version &&
          excluded_services_config == o.excluded_services_config &&
          network_properties == o.network_properties &&
          compute_isolation_properties == o.compute_isolation_properties &&
          private_link_configurations == o.private_link_configurations &&
          private_endpoint_connections == o.private_endpoint_connections
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cluster_version, cluster_hdp_version, os_type, tier, cluster_id, cluster_definition, kafka_rest_properties, security_profile, compute_profile, provisioning_state, created_date, cluster_state, quota_info, errors, connectivity_endpoints, disk_encryption_properties, encryption_in_transit_properties, storage_profile, min_supported_tls_version, excluded_services_config, network_properties, compute_isolation_properties, private_link_configurations, private_endpoint_connections].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

  end
end