=begin
#KeyVaultManagementClient

#The Azure management API provides a RESTful set of web services that interact with Azure Key Vault.

The version of the OpenAPI document: 2026-05-15

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::JsonWebKeyOperation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::JsonWebKeyOperation do
  #let(:instance) { AzureRest::JsonWebKeyOperation.new }

  describe 'test an instance of JsonWebKeyOperation' do
    it 'should create an instance of JsonWebKeyOperation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::JsonWebKeyOperation)
    end
  end

end
