=begin
#KeyVaultManagementClient

#The Azure management API provides a RESTful set of web services that interact with Azure Key Vault.

The version of the OpenAPI document: 2026-05-15

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::ManagedHsmKeyRotationPolicyAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::ManagedHsmKeyRotationPolicyAttributes do
  #let(:instance) { AzureSDK::ManagedHsmKeyRotationPolicyAttributes.new }

  describe 'test an instance of ManagedHsmKeyRotationPolicyAttributes' do
    it 'should create an instance of ManagedHsmKeyRotationPolicyAttributes' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::ManagedHsmKeyRotationPolicyAttributes)
    end
  end

  describe 'test attribute "created"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "updated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expiry_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
