=begin
#KeyVaultManagementClient

#The Azure management API provides a RESTful set of web services that interact with Azure Key Vault.

The version of the OpenAPI document: 2026-05-15

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::VaultPatchParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::VaultPatchParameters do
  #let(:instance) { AzureRest::VaultPatchParameters.new }

  describe 'test an instance of VaultPatchParameters' do
    it 'should create an instance of VaultPatchParameters' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::VaultPatchParameters)
    end
  end

  describe 'test attribute "tags"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "properties"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
