=begin
#PostgreSQLManagementClient

#The Azure Database for PostgreSQL management API provides create, read, update, and delete functionality for Azure PostgreSQL resources including servers, databases, firewall rules, network configuration, security alert policies, log files and configurations with new business model.

The version of the OpenAPI document: 2025-08-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'date'
require 'time'

module AzureRest
  module PostgreSQL
  class ServerState
    READY = "Ready".freeze
    DROPPING = "Dropping".freeze
    DISABLED = "Disabled".freeze
    STARTING = "Starting".freeze
    STOPPING = "Stopping".freeze
    STOPPED = "Stopped".freeze
    UPDATING = "Updating".freeze
    RESTARTING = "Restarting".freeze
    INACCESSIBLE = "Inaccessible".freeze
    PROVISIONING = "Provisioning".freeze

    def self.all_vars
      @all_vars ||= [READY, DROPPING, DISABLED, STARTING, STOPPING, STOPPED, UPDATING, RESTARTING, INACCESSIBLE, PROVISIONING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ServerState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ServerState"
    end
  end
  end
end