=begin
#PostgreSQLManagementClient

#The Azure Database for PostgreSQL management API provides create, read, update, and delete functionality for Azure PostgreSQL resources including servers, databases, firewall rules, network configuration, security alert policies, log files and configurations with new business model.

The version of the OpenAPI document: 2025-08-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::BackupAutomaticAndOnDemandsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BackupAutomaticAndOnDemandsApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::BackupAutomaticAndOnDemandsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BackupAutomaticAndOnDemandsApi' do
    it 'should create an instance of BackupAutomaticAndOnDemandsApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::BackupAutomaticAndOnDemandsApi)
    end
  end

  # unit tests for backups_automatic_and_on_demand_create
  # Creates an on demand backup of a server.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param backup_name Name of the backup.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'backups_automatic_and_on_demand_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for backups_automatic_and_on_demand_delete
  # Deletes a specific backup, given its name.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param backup_name Name of the backup.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'backups_automatic_and_on_demand_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for backups_automatic_and_on_demand_get
  # Gets information of an on demand backup, given its name.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param backup_name Name of the backup.
  # @param [Hash] opts the optional parameters
  # @return [BackupAutomaticAndOnDemand]
  describe 'backups_automatic_and_on_demand_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for backups_automatic_and_on_demand_list_by_server
  # Lists all available backups of a server.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param [Hash] opts the optional parameters
  # @return [BackupAutomaticAndOnDemandList]
  describe 'backups_automatic_and_on_demand_list_by_server test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
