=begin
#PostgreSQLManagementClient

#The Azure Database for PostgreSQL management API provides create, read, update, and delete functionality for Azure PostgreSQL resources including servers, databases, firewall rules, network configuration, security alert policies, log files and configurations with new business model.

The version of the OpenAPI document: 2025-08-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::PrivateEndpointConnectionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrivateEndpointConnectionsApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::PrivateEndpointConnectionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrivateEndpointConnectionsApi' do
    it 'should create an instance of PrivateEndpointConnectionsApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::PrivateEndpointConnectionsApi)
    end
  end

  # unit tests for private_endpoint_connections_delete
  # Deletes a private endpoint connection.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param private_endpoint_connection_name The name of the private endpoint connection associated with the Azure resource.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'private_endpoint_connections_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_endpoint_connections_get
  # Gets a private endpoint connection.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param private_endpoint_connection_name The name of the private endpoint connection associated with the Azure resource.
  # @param [Hash] opts the optional parameters
  # @return [PrivateEndpointConnection]
  describe 'private_endpoint_connections_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_endpoint_connections_list_by_server
  # Lists all private endpoint connections on a server.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param [Hash] opts the optional parameters
  # @return [PrivateEndpointConnectionList]
  describe 'private_endpoint_connections_list_by_server test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for private_endpoint_connections_update
  # Approves or rejects a private endpoint connection.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription. The value must be an UUID.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param server_name The name of the server.
  # @param private_endpoint_connection_name The name of the private endpoint connection associated with the Azure resource.
  # @param parameters Parameters required to update a private endpoint connection.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'private_endpoint_connections_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
