=begin
#HDInsightManagementClient

#The HDInsight Management Client.

The version of the OpenAPI document: 2021-06-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::ClusterDiskEncryptionParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::ClusterDiskEncryptionParameters do
  #let(:instance) { AzureSDK::ClusterDiskEncryptionParameters.new }

  describe 'test an instance of ClusterDiskEncryptionParameters' do
    it 'should create an instance of ClusterDiskEncryptionParameters' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::ClusterDiskEncryptionParameters)
    end
  end

  describe 'test attribute "vault_uri"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "key_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "key_version"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
