=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-03-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::DdosTcpPerSourceRateLimitPolicy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::DdosTcpPerSourceRateLimitPolicy do
  #let(:instance) { AzureRest::DdosTcpPerSourceRateLimitPolicy.new }

  describe 'test an instance of DdosTcpPerSourceRateLimitPolicy' do
    it 'should create an instance of DdosTcpPerSourceRateLimitPolicy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::DdosTcpPerSourceRateLimitPolicy)
    end
  end

  describe 'test attribute "packets_per_second"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
