=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::DdosTrafficType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::DdosTrafficType do
  #let(:instance) { AzureRest::DdosTrafficType.new }

  describe 'test an instance of DdosTrafficType' do
    it 'should create an instance of DdosTrafficType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::DdosTrafficType)
    end
  end

end
