=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::IPConfigurationPropertiesFormat2
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::IPConfigurationPropertiesFormat2 do
  #let(:instance) { AzureSDK::IPConfigurationPropertiesFormat2.new }

  describe 'test an instance of IPConfigurationPropertiesFormat2' do
    it 'should create an instance of IPConfigurationPropertiesFormat2' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::IPConfigurationPropertiesFormat2)
    end
  end

  describe 'test attribute "private_ip_address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "private_ip_allocation_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "subnet"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "public_ip_address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "provisioning_state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
