=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureSDK::NetworkProfilePropertiesFormat
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureSDK::NetworkProfilePropertiesFormat do
  #let(:instance) { AzureSDK::NetworkProfilePropertiesFormat.new }

  describe 'test an instance of NetworkProfilePropertiesFormat' do
    it 'should create an instance of NetworkProfilePropertiesFormat' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureSDK::NetworkProfilePropertiesFormat)
    end
  end

  describe 'test attribute "container_network_interfaces"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "container_network_interface_configurations"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "resource_guid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "provisioning_state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
