=begin
#WebApplicationFirewallManagement

#APIs to manage Microsoft Azure network resources.

The version of the OpenAPI document: 2026-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureRest::VirtualApplianceIPConfigurationProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureRest::VirtualApplianceIPConfigurationProperties do
  #let(:instance) { AzureRest::VirtualApplianceIPConfigurationProperties.new }

  describe 'test an instance of VirtualApplianceIPConfigurationProperties' do
    it 'should create an instance of VirtualApplianceIPConfigurationProperties' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(AzureRest::VirtualApplianceIPConfigurationProperties)
    end
  end

  describe 'test attribute "primary"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
