=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::DedicatedHostApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DedicatedHostApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::DedicatedHostApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DedicatedHostApi' do
    it 'should create an instance of DedicatedHostApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::DedicatedHostApi)
    end
  end

  # unit tests for dedicated_hosts_list_available_sizes
  # Lists all available dedicated host sizes to which the specified dedicated host can be resized. NOTE: The dedicated host sizes provided can be used to only scale up the existing dedicated host.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param host_group_name The name of the dedicated host group.
  # @param host_name The name of the dedicated host.
  # @param [Hash] opts the optional parameters
  # @return [DedicatedHostSizeListResult]
  describe 'dedicated_hosts_list_available_sizes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for dedicated_hosts_list_by_host_group
  # Lists all of the dedicated hosts in the specified dedicated host group. Use the nextLink property in the response to get the next page of dedicated hosts.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param host_group_name The name of the dedicated host group.
  # @param [Hash] opts the optional parameters
  # @return [DedicatedHostListResult]
  describe 'dedicated_hosts_list_by_host_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for dedicated_hosts_redeploy
  # Redeploy the dedicated host. The operation will complete successfully once the dedicated host has migrated to a new node and is running. To determine the health of VMs deployed on the dedicated host after the redeploy check the Resource Health Center in the Azure Portal. Please refer to https://docs.microsoft.com/azure/service-health/resource-health-overview for more details.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param host_group_name The name of the dedicated host group.
  # @param host_name The name of the dedicated host.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'dedicated_hosts_redeploy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for dedicated_hosts_restart
  # Restart the dedicated host. The operation will complete successfully once the dedicated host has restarted and is running. To determine the health of VMs deployed on the dedicated host after the restart check the Resource Health Center in the Azure Portal. Please refer to https://docs.microsoft.com/azure/service-health/resource-health-overview for more details.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param host_group_name The name of the dedicated host group.
  # @param host_name The name of the dedicated host.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'dedicated_hosts_restart test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
