=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureSDK::LogAnalyticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LogAnalyticsApi' do
  before do
    # run before each test
    @api_instance = AzureSDK::LogAnalyticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogAnalyticsApi' do
    it 'should create an instance of LogAnalyticsApi' do
      expect(@api_instance).to be_instance_of(AzureSDK::LogAnalyticsApi)
    end
  end

  # unit tests for log_analytics_export_request_rate_by_interval
  # Export logs that show Api requests made by this subscription in the given time window to show throttling activities.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param location The name of Azure region.
  # @param parameters Parameters supplied to the LogAnalytics getRequestRateByInterval Api.
  # @param [Hash] opts the optional parameters
  # @return [LogAnalyticsOperationResult]
  describe 'log_analytics_export_request_rate_by_interval test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for log_analytics_export_throttled_requests
  # Export logs that show total throttled Api requests for this subscription in the given time window.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param location The name of Azure region.
  # @param parameters The request body
  # @param [Hash] opts the optional parameters
  # @return [LogAnalyticsOperationResult]
  describe 'log_analytics_export_throttled_requests test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
