=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::VirtualMachineScaleSetVMsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VirtualMachineScaleSetVMsApi' do
  before do
    # run before each test
    @api_instance = AzureRest::VirtualMachineScaleSetVMsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VirtualMachineScaleSetVMsApi' do
    it 'should create an instance of VirtualMachineScaleSetVMsApi' do
      expect(@api_instance).to be_instance_of(AzureRest::VirtualMachineScaleSetVMsApi)
    end
  end

  # unit tests for virtual_machine_scale_set_vms_approve_rolling_upgrade
  # Approve upgrade on deferred rolling upgrade for OS disk on a VM scale set instance.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_approve_rolling_upgrade test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_attach_detach_data_disks
  # Attach and detach data disks to/from a virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param parameters Parameters supplied to the attach and detach data disks operation on a Virtual Machine Scale Sets VM.
  # @param [Hash] opts the optional parameters
  # @return [StorageProfile]
  describe 'virtual_machine_scale_set_vms_attach_detach_data_disks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_deallocate
  # Deallocates a specific virtual machine in a VM scale set. Shuts down the virtual machine and releases the compute resources it uses. You are not billed for the compute resources of this virtual machine once it is deallocated.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_deallocate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_delete
  # Deletes a virtual machine from a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :force_deletion Optional parameter to force delete a virtual machine from a VM scale set. (Feature in Preview)
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_get
  # Gets a virtual machine from a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand The expand expression to apply on the operation. &#39;InstanceView&#39; will retrieve the instance view of the virtual machine. &#39;UserData&#39; will retrieve the UserData of the virtual machine.
  # @return [VirtualMachineScaleSetVM]
  describe 'virtual_machine_scale_set_vms_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_get_instance_view
  # Gets the status of a virtual machine from a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [VirtualMachineScaleSetVMInstanceView]
  describe 'virtual_machine_scale_set_vms_get_instance_view test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_list
  # Gets a list of all virtual machines in a VM scale sets.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param virtual_machine_scale_set_name The name of the VirtualMachineScaleSet
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter The filter to apply to the operation. Allowed values are &#39;startswith(instanceView/statuses/code, &#39;PowerState&#39;) eq true&#39;, &#39;properties/latestModelApplied eq true&#39;, &#39;properties/latestModelApplied eq false&#39;.
  # @option opts [String] :select The list parameters. Allowed values are &#39;instanceView&#39;, &#39;instanceView/statuses&#39;.
  # @option opts [String] :expand The expand expression to apply to the operation. Allowed values are &#39;instanceView&#39;.
  # @return [VirtualMachineScaleSetVMListResult]
  describe 'virtual_machine_scale_set_vms_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_perform_maintenance
  # Performs maintenance on a virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_perform_maintenance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_power_off
  # Power off (stop) a virtual machine in a VM scale set. Note that resources are still attached and you are getting charged for the resources. Instead, use deallocate to release resources and avoid charges.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :skip_shutdown The parameter to request non-graceful VM shutdown. True value for this flag indicates non-graceful shutdown whereas false indicates otherwise. Default value for this flag is false if not specified
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_power_off test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_redeploy
  # Shuts down the virtual machine in the virtual machine scale set, moves it to a new node, and powers it back on.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_redeploy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_reimage
  # Reimages (upgrade the operating system) a specific virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @option opts [VirtualMachineScaleSetVMReimageParameters] :vm_scale_set_vm_reimage_input Parameters for the Reimaging Virtual machine in ScaleSet.
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_reimage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_reimage_all
  # Allows you to re-image all the disks ( including data disks ) in the a VM scale set instance. This operation is only supported for managed disks.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_reimage_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_restart
  # Restarts a virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_restart test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_retrieve_boot_diagnostics_data
  # The operation to retrieve SAS URIs of boot diagnostic logs for a virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :sas_uri_expiration_time_in_minutes Expiration duration in minutes for the SAS URIs with a value between 1 to 1440 minutes. **Note:** If not specified, SAS URIs will be generated with a default expiration duration of 120 minutes.
  # @return [RetrieveBootDiagnosticsDataResult]
  describe 'virtual_machine_scale_set_vms_retrieve_boot_diagnostics_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_run_command
  # Run command on a virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param parameters Parameters supplied to the Run command operation.
  # @param [Hash] opts the optional parameters
  # @return [RunCommandResult]
  describe 'virtual_machine_scale_set_vms_run_command test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_simulate_eviction
  # The operation to simulate the eviction of spot virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_simulate_eviction test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_start
  # Starts a virtual machine in a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'virtual_machine_scale_set_vms_start test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_vms_update
  # Updates a virtual machine of a VM scale set.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param instance_id The instance ID of the virtual machine.
  # @param parameters Parameters supplied to the Update Virtual Machine Scale Sets VM operation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_match The ETag of the transformation. Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting concurrent changes.
  # @option opts [String] :if_none_match Set to &#39;*&#39; to allow a new record set to be created, but to prevent updating an existing record set. Other values will result in error from server as they are not supported.
  # @return [VirtualMachineScaleSetVM]
  describe 'virtual_machine_scale_set_vms_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
