=begin
#Azure Compute resource management API.

#Compute Client

The version of the OpenAPI document: 2026-04-01

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureRest::VirtualMachineScaleSetLifeCycleHookEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VirtualMachineScaleSetLifeCycleHookEventsApi' do
  before do
    # run before each test
    @api_instance = AzureRest::VirtualMachineScaleSetLifeCycleHookEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VirtualMachineScaleSetLifeCycleHookEventsApi' do
    it 'should create an instance of VirtualMachineScaleSetLifeCycleHookEventsApi' do
      expect(@api_instance).to be_instance_of(AzureRest::VirtualMachineScaleSetLifeCycleHookEventsApi)
    end
  end

  # unit tests for virtual_machine_scale_set_life_cycle_hook_events_get
  # Gets a virtual machine scale set lifecycle hook event.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param lifecycle_hook_event_name The name of the VMScaleSetLifecycleHookEvent
  # @param [Hash] opts the optional parameters
  # @return [VMScaleSetLifecycleHookEvent]
  describe 'virtual_machine_scale_set_life_cycle_hook_events_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_life_cycle_hook_events_list
  # Gets a list of virtual machine scale set lifecycle hook events created for a virtual machine scale set resource.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param [Hash] opts the optional parameters
  # @return [VMScaleSetLifecycleHookEventListResult]
  describe 'virtual_machine_scale_set_life_cycle_hook_events_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for virtual_machine_scale_set_life_cycle_hook_events_update
  # The operation to update a virtual machine scale set lifecycle hook event.
  # @param api_version The API version to use for this operation.
  # @param subscription_id The ID of the target subscription.
  # @param resource_group_name The name of the resource group. The name is case insensitive.
  # @param vm_scale_set_name The name of the VM scale set.
  # @param lifecycle_hook_event_name The name of the VMScaleSetLifecycleHookEvent
  # @param properties Parameters supplied to the Update virtual machine scale set lifecycle hook event operation.
  # @param [Hash] opts the optional parameters
  # @return [VMScaleSetLifecycleHookEvent]
  describe 'virtual_machine_scale_set_life_cycle_hook_events_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
